/**
 * Name: Johnny Garcia
 * Date: 9/13/2025
* Purpose: Lab3 - 

// Don't forget to import and declare a Scanner for user input.

public class Lab3_Johnny_Garcia
{
    public static void main(String[] args) 
    {
        // In-Class 3 Example:
        // Step 1: Prompt the user to enter the length of the side of a cube.
        // Step 2: Read the user's input and store it in a variable.
        // Step 3: Use an appropriate method to determine the volume of the cube.
        // Step 4: Use an appropriate method to determine the surface area of the cube.
        // HINT: Steps 3 and 4 will use the Math.pow(a, b) method
        // Step 5: Print the volume and surface area in clear sentences.
    }
}